# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         base
version:      2.03
version_from: lib/base.pm
installdirs:  perl
requires:
    Test::More:                    0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
